definitions:
  request.CreateAuthTokenRequest:
    properties:
      password:
        description: 登陆密码
        type: string
      username:
        description: 登陆用户
        type: string
    required:
    - password
    - username
    type: object
  request.EditUserRequest:
    properties:
      nickname:
        description: 用户别名
        type: string
      username:
        description: 登录名
        type: string
    required:
    - nickname
    - username
    type: object
  response.Result:
    properties:
      code:
        description: 业务码
        type: integer
      data:
        description: 业务消息体
      msg:
        description: 业务消息
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  description: gin-skeleton 示例项目
  title: gin-skeleton
  version: "1.0"
paths:
  /api/auth/logout:
    get:
      consumes:
      - application/json
      description: 退出登录
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      security:
      - BearerAuth: []
      summary: 退出登录
      tags:
      - 授权管理
  /api/auth/token:
    post:
      consumes:
      - application/json
      description: 令牌创建
      parameters:
      - description: 用户名, 密码
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/request.CreateAuthTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 令牌创建
      tags:
      - 授权管理
  /api/auth/user:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      security:
      - BearerAuth: []
      summary: 获取用户信息
      tags:
      - 授权管理
  /api/ping:
    get:
      consumes:
      - application/json
      description: 服务健康
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 服务健康
      tags:
      - 基础管理
  /api/user/{uid}:
    get:
      consumes:
      - application/json
      description: 获取用户详情
      parameters:
      - description: user ID
        in: path
        name: uid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      security:
      - BearerAuth: []
      summary: 获取用户详情
      tags:
      - 用户管理
  /api/user/edit:
    post:
      consumes:
      - application/json
      description: 修改基础信息
      parameters:
      - description: 用户名, 用户呢称
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/request.EditUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      security:
      - BearerAuth: []
      summary: 修改基础信息
      tags:
      - 用户管理
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
